//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualLabelDesigner.ZplTextEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RegularStyleColor {
            get {
                return ((global::System.Drawing.Color)(this["RegularStyleColor"]));
            }
            set {
                this["RegularStyleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color CommentStyleColor {
            get {
                return ((global::System.Drawing.Color)(this["CommentStyleColor"]));
            }
            set {
                this["CommentStyleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color FunctionStyleColor {
            get {
                return ((global::System.Drawing.Color)(this["FunctionStyleColor"]));
            }
            set {
                this["FunctionStyleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkViolet")]
        public global::System.Drawing.Color OptionsStyleColor {
            get {
                return ((global::System.Drawing.Color)(this["OptionsStyleColor"]));
            }
            set {
                this["OptionsStyleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brown")]
        public global::System.Drawing.Color StringStyleColor {
            get {
                return ((global::System.Drawing.Color)(this["StringStyleColor"]));
            }
            set {
                this["StringStyleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color VariableStyleColor {
            get {
                return ((global::System.Drawing.Color)(this["VariableStyleColor"]));
            }
            set {
                this["VariableStyleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#V")]
        public string VariableStartChars {
            get {
                return ((string)(this["VariableStartChars"]));
            }
            set {
                this["VariableStartChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#V")]
        public string VariableEndChars {
            get {
                return ((string)(this["VariableEndChars"]));
            }
            set {
                this["VariableEndChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string EditorFontFamily {
            get {
                return ((string)(this["EditorFontFamily"]));
            }
            set {
                this["EditorFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string EditorFontSize {
            get {
                return ((string)(this["EditorFontSize"]));
            }
            set {
                this["EditorFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplaceSpecialChar {
            get {
                return ((bool)(this["ReplaceSpecialChar"]));
            }
            set {
                this["ReplaceSpecialChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ToolboxDisplayOrder {
            get {
                return ((int)(this["ToolboxDisplayOrder"]));
            }
            set {
                this["ToolboxDisplayOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bShowHelp {
            get {
                return ((bool)(this["bShowHelp"]));
            }
            set {
                this["bShowHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bShowZPLCode {
            get {
                return ((bool)(this["bShowZPLCode"]));
            }
            set {
                this["bShowZPLCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bShowPreview {
            get {
                return ((bool)(this["bShowPreview"]));
            }
            set {
                this["bShowPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string zplRenderEngine {
            get {
                return ((string)(this["zplRenderEngine"]));
            }
            set {
                this["zplRenderEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10.1.5.107 @ ZTC ZM600-200dpi ZPL</string>
  <string>10.1.5.108 @ ZTC ZM600-200dpi ZPL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecentPrinter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentPrinter"]));
            }
            set {
                this["RecentPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VariableSubstitutionEnabled {
            get {
                return ((bool)(this["VariableSubstitutionEnabled"]));
            }
            set {
                this["VariableSubstitutionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsPreviewPinned {
            get {
                return ((bool)(this["IsPreviewPinned"]));
            }
            set {
                this["IsPreviewPinned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedLabelId {
            get {
                return ((int)(this["SelectedLabelId"]));
            }
            set {
                this["SelectedLabelId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ToolboxDistance {
            get {
                return ((int)(this["ToolboxDistance"]));
            }
            set {
                this["ToolboxDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomPercent {
            get {
                return ((string)(this["ZoomPercent"]));
            }
            set {
                this["ZoomPercent"] = value;
            }
        }
    }
}
