//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonDock.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvalonDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string DockableContentCommands_DockableFloatingWindow {
            get {
                return ResourceManager.GetString("DockableContentCommands_DockableFloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string DockableContentCommands_FloatingWindow {
            get {
                return ResourceManager.GetString("DockableContentCommands_FloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock as Tabbed Document 的本地化字符串。
        /// </summary>
        public static string DockableContentCommands_ShowAsDocument {
            get {
                return ResourceManager.GetString("DockableContentCommands_ShowAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Hide 的本地化字符串。
        /// </summary>
        public static string DockableContentCommands_ToggleAutoHide {
            get {
                return ResourceManager.GetString("DockableContentCommands_ToggleAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Position 的本地化字符串。
        /// </summary>
        public static string DockablePane_ShowOptionsMenu {
            get {
                return ResourceManager.GetString("DockablePane_ShowOptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string DockablePaneCommands_Close {
            get {
                return ResourceManager.GetString("DockablePaneCommands_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string DockablePaneCommands_Hide {
            get {
                return ResourceManager.GetString("DockablePaneCommands_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Hide 的本地化字符串。
        /// </summary>
        public static string DockablePaneCommands_ToggleAutoHide {
            get {
                return ResourceManager.GetString("DockablePaneCommands_ToggleAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string DocumentContentCommands_FloatingDocument {
            get {
                return ResourceManager.GetString("DocumentContentCommands_FloatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock as Tabbed Document 的本地化字符串。
        /// </summary>
        public static string DocumentContentCommands_TabbedDocument {
            get {
                return ResourceManager.GetString("DocumentContentCommands_TabbedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All But This 的本地化字符串。
        /// </summary>
        public static string DocumentPaneCommands_CloseAllButThis {
            get {
                return ResourceManager.GetString("DocumentPaneCommands_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string DocumentPaneCommands_CloseThis {
            get {
                return ResourceManager.GetString("DocumentPaneCommands_CloseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Horizontal Tab Group 的本地化字符串。
        /// </summary>
        public static string DocumentPaneCommands_NewHorizontalTabGroup {
            get {
                return ResourceManager.GetString("DocumentPaneCommands_NewHorizontalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New VerticalTab Group 的本地化字符串。
        /// </summary>
        public static string DocumentPaneCommands_NewVerticalTabGroup {
            get {
                return ResourceManager.GetString("DocumentPaneCommands_NewVerticalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate 的本地化字符串。
        /// </summary>
        public static string ManagedContentCommands_Activate {
            get {
                return ResourceManager.GetString("ManagedContentCommands_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string ManagedContentCommands_Close {
            get {
                return ResourceManager.GetString("ManagedContentCommands_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string ManagedContentCommands_Hide {
            get {
                return ResourceManager.GetString("ManagedContentCommands_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string ManagedContentCommands_Show {
            get {
                return ResourceManager.GetString("ManagedContentCommands_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Files 的本地化字符串。
        /// </summary>
        public static string NavigatorWindow_ActiveFiles {
            get {
                return ResourceManager.GetString("NavigatorWindow_ActiveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Tool Windows 的本地化字符串。
        /// </summary>
        public static string NavigatorWindow_ActiveToolWindows {
            get {
                return ResourceManager.GetString("NavigatorWindow_ActiveToolWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock 的本地化字符串。
        /// </summary>
        public static string PaneCommands_Dock {
            get {
                return ResourceManager.GetString("PaneCommands_Dock", resourceCulture);
            }
        }
    }
}
